name: Deploy to Azure Web App

# This script is ONLY run when the code has already been merged into main
on:
  push:
    branches: [ "main" ]

env:
  AZURE_WEBAPP_NAME: 'reatstracker-api' 
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Upload the code
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Installing .NET
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    # 3. Downloading packages
    - name: Restore dependencies
      run: dotnet restore ReatsTracker.Api/ReatsTracker.Api.csproj

    # 4. Compile and collect the finished files into the ./publish folder
    - name: Build and Publish
      run: |
        dotnet build ReatsTracker.Api/ReatsTracker.Api.csproj --configuration Release --no-restore
        dotnet publish ReatsTracker.Api/ReatsTracker.Api.csproj --configuration Release --no-build --output ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish