name: Deploy to Azure (Staging & Prod)

on:
  push:
    branches: [ "main" ]

env:
  AZURE_WEBAPP_NAME_STAGING: 'reatstracker-api-staging' 
  AZURE_WEBAPP_NAME_PROD: 'reatstracker-api'            
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore ReatsTracker.Api/ReatsTracker.Api.csproj

    # Automatic database migrations
    - name: Install EF Core CLI
      run: dotnet tool install --global dotnet-ef

    - name: Apply Database Migrations
      run: dotnet ef database update --project ReatsTracker.Api/ReatsTracker.Api.csproj --connection "${{ secrets.DB_CONNECTION_STRING }}"

    # Project assembly
    - name: Build and Publish
      run: |
        dotnet build ReatsTracker.Api/ReatsTracker.Api.csproj --configuration Release --no-restore
        dotnet publish ReatsTracker.Api/ReatsTracker.Api.csproj --configuration Release --no-build --output ./publish

    # --- DEPLOY ON STAGING ---
    - name: Deploy to Staging
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME_STAGING }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_STAGING }}
        package: ./publish


    # --- DEPLOY ON PRODUCTION ---
    - name: Deploy to Production
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME_PROD }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish
        